//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagenesxReceta
    {
        public int ImageId { get; set; }
        public int Id_receta { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Recetas Recetas { get; set; }
    }
}
