//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class recetasxIngredientes
    {
        public int Id_ingredientes { get; set; }
        public int Id_receta { get; set; }
        public int cantidad { get; set; }
        public string unidad { get; set; }
    
        public virtual Ingredientes Ingredientes { get; set; }
        public virtual Recetas Recetas { get; set; }
    }
}
